use_frameworks!
use_modular_headers!

platform :ios, '10.0'

target 'Saiha_Example' do
  pod 'Saiha', :path => '../'
  
  pod 'SDWebImage'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 10.0
      #config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = 11.0
    end
  end
end
